#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
# Gradle start up script for POSIX generated by Gradle.
#
# Important for running:
#
# (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#     noncompliant, but you have some other compliant shell such as ksh or
#     bash, then to run this script, type that shell name before the whole
#     file name, like instead of executing this:
#
#         $ ./gradlew clean assemble
#
#     you can run:
#
#         $ bash gradlew clean assemble
#
# Normally on unices you don't need this, but when the your version of
# getopt doesn't understand `long options' then you'll want to convert this
# to use the old-style getopt.
##############################################################################
if (( $+commands[getopt] )); then
    set -- $(getopt -o h --long help -- "$@")
else
    set -- "$@"
fi

while true; do
    case "$1" in
        -h|--help) echo "Gradle wrapper script"; exit 0 ;;
        *) break ;;
    esac
done

##############################################################################
# Start Gradle
##############################################################################
if [ -z "$GRADLE_HOME" ] ; then
  if [ ! -d "$APP_HOME/gradle/wrapper" ] ; then
    echo "Error: GRADLE_HOME is not set and this project is not using gradle wrapper."
    exit 1
  fi
  GRADLE_HOME="$APP_HOME/gradle/wrapper"
fi

if [ ! -x "$GRADLE_HOME/gradlew" ] ; then
  echo "Error: gradlew not found in $GRADLE_HOME"
  exit 1
fi

APP_BASE_NAME=$(basename "$0")
cd "$(dirname "$0")" || exit

# Attempt to set APP_HOME
APP_HOME=$PWD

# Try to locate gradle
if [ ! -f "$APP_HOME/gradlew" ] ; then
  echo "This script should be run from the root directory of the Gradle project."
  exit 1
fi

# Set the GRADLE executable
GRADLE_SCRIPT=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

exec "$JAVA_HOME/bin/java" -Dorg.gradle.appname="$APP_BASE_NAME" -classpath "$GRADLE_SCRIPT" org.gradle.wrapper.GradleWrapperMain "$@"
