#!/usr/bin/env python3
"""
AstraRoot Boot Image Patcher v2

Injects astra_root.ko + astrad + astra_su into vendor_boot/boot ramdisk,
so the device auto-loads the kernel module and starts the daemon on boot.

Supported boot header versions: v0-v4
Supported ramdisk compression: lz4, gzip, zstd, uncompressed
Supported partitions: boot.img, vendor_boot.img, init_boot.img

Usage:
  python3 patch_boot.py \
    --boot vendor_boot.img \
    --module kernel/astra_root.ko \
    --daemon daemon/build/astrad \
    --su native/astra_su \
    --output vendor_boot_patched.img

Flash:
  adb reboot bootloader
  fastboot flash vendor_boot vendor_boot_patched.img
  fastboot flash vbmeta --disable-verity --disable-verification vbmeta.img
  fastboot reboot
"""

import argparse
import hashlib
import os
import shutil
import struct
import subprocess
import sys
import tempfile
from pathlib import Path


class BootImageError(Exception):
    pass


def run_cmd(cmd: list, cwd=None, check=True, capture=True):
    """Execute external command"""
    print(f"  $ {' '.join(cmd)}")
    result = subprocess.run(
        cmd, cwd=cwd, check=check,
        capture_output=capture, text=True
    )
    if result.returncode != 0 and check:
        raise BootImageError(f"Command failed: {result.stderr}")
    return result


def detect_compression(filepath: str) -> str:
    """Detect file compression format"""
    with open(filepath, 'rb') as f:
        magic = f.read(8)

    if magic[:4] == b'\x02\x21\x4c\x18':
        return 'lz4'
    elif magic[:2] == b'\x1f\x8b':
        return 'gzip'
    elif magic[:4] == b'\x28\xb5\x2f\xfd':
        return 'zstd'
    elif magic[:6] == b'\xfd7zXZ\x00':
        return 'xz'
    elif magic[:4] == b'BZh9':
        return 'bzip2'
    else:
        return 'none'


def decompress(input_path: str, output_path: str, fmt: str):
    """Decompress file"""
    if fmt == 'lz4':
        run_cmd(['lz4', '-d', '-f', input_path, output_path])
    elif fmt == 'gzip':
        result = run_cmd(['gzip', '-d', '-c', input_path])
        with open(output_path, 'wb') as f:
            f.write(result.stdout.encode('latin-1') if isinstance(result.stdout, str) else result.stdout)
    elif fmt == 'zstd':
        run_cmd(['zstd', '-d', '-f', input_path, '-o', output_path])
    elif fmt == 'xz':
        run_cmd(['xz', '-d', '-k', '-c', input_path, output_path])
    elif fmt == 'bzip2':
        run_cmd(['bzip2', '-d', '-c', input_path, output_path])
    else:
        shutil.copy2(input_path, output_path)


def compress(input_path: str, output_path: str, fmt: str):
    """Compress file"""
    if fmt == 'lz4':
        run_cmd(['lz4', '-9', '-f', input_path, output_path])
    elif fmt == 'gzip':
        result = run_cmd(['gzip', '-9', '-c', input_path])
        with open(output_path, 'wb') as f:
            f.write(result.stdout.encode('latin-1') if isinstance(result.stdout, str) else result.stdout)
    elif fmt == 'zstd':
        run_cmd(['zstd', '-19', '-f', input_path, '-o', output_path])
    elif fmt == 'xz':
        run_cmd(['xz', '-z', '-k', '-c', input_path, output_path])
    elif fmt == 'bzip2':
        run_cmd(['bzip2', '-z', '-c', input_path, output_path])
    else:
        shutil.copy2(input_path, output_path)


def unpack_cpio(cpio_path: str, output_dir: str):
    """Unpack CPIO archive"""
    os.makedirs(output_dir, exist_ok=True)
    with open(cpio_path, 'rb') as f:
        data = f.read()
    proc = subprocess.run(
        ['cpio', '-idmv', '--no-absolute-filenames'],
        cwd=output_dir, input=data,
        capture_output=True
    )
    if proc.returncode != 0:
        # Try --unsafe mode
        proc = subprocess.run(
            ['cpio', '-idmv', '--no-absolute-filenames', '--unsafe'],
            cwd=output_dir, input=data,
            capture_output=True
        )


def repack_cpio(input_dir: str, output_path: str):
    """Repack CPIO archive"""
    result = subprocess.run(
        ['find', '.', '-print0'],
        cwd=input_dir, capture_output=True
    )
    files = result.stdout

    proc = subprocess.run(
        ['cpio', '-o', '-H', 'newc', '--null'],
        cwd=input_dir, input=files,
        capture_output=True
    )
    with open(output_path, 'wb') as f:
        f.write(proc.stdout)


def create_init_script(output_dir: str, has_daemon: bool, has_su: bool):
    """Create AstraRoot init script"""
    script = """#!/system/bin/sh
# AstraRoot init script
# Auto-generated by AstraVeil Boot Patcher

LOG_TAG="AstraRoot.Init"
log() { echo "[${LOG_TAG}] $1" > /dev/kmsg 2>/dev/null; }

log "AstraRoot init starting..."

# -- Step 1: load kernel module --
if [ -f /lib/modules/astra_root.ko ]; then
    insmod /lib/modules/astra_root.ko enforce=0
    if [ $? -eq 0 ]; then
        log "astra_root.ko loaded successfully"
    else
        log "ERROR: failed to load astra_root.ko"
    fi
else
    log "WARNING: astra_root.ko not found"
fi

# -- Step 2: wait for device node --
WAIT=0
while [ ! -e /dev/astra_root ] && [ $WAIT -lt 10 ]; do
    sleep 1
    WAIT=$((WAIT + 1))
done

if [ -e /dev/astra_root ]; then
    chmod 0666 /dev/astra_root
    log "/dev/astra_root ready"
else
    log "ERROR: /dev/astra_root not found after 10s"
fi

# -- Step 3: create directory structure --
mkdir -p /dev/astra
chmod 0755 /dev/astra
mkdir -p /data/adb/astraveil
chmod 0755 /data/adb/astraveil
"""

    if has_daemon:
        script += """
# -- Step 4: start astrad --
ASTRAD="/data/adb/astraveil/astrad"
if [ -f "$ASTRAD" ]; then
    chmod 0755 "$ASTRAD"
    nohup "$ASTRAD" --socket /dev/astra/astrad.sock > /data/adb/astraveil/astrad.log 2>&1 &
    ASTRA_PID=$!
    log "astrad started (pid=$ASTRA_PID)"

    # wait for socket
    WAIT=0
    while [ ! -S /dev/astra/astrad.sock ] && [ $WAIT -lt 10 ]; do
        sleep 1
        WAIT=$((WAIT + 1))
    done

    if [ -S /dev/astra/astrad.sock ]; then
        chmod 0666 /dev/astra/astrad.sock
        log "astrad socket ready"
    else
        log "WARNING: astrad socket not ready"
    fi
else
    log "WARNING: astrad not found at $ASTRAD"
fi
"""

    if has_su:
        script += """
# -- Step 5: install su --
ASTRA_SU="/data/adb/astraveil/astra_su"
if [ -f "$ASTRA_SU" ]; then
    chmod 0755 "$ASTRA_SU"
    # mount tmpfs on /sbin if it doesn't exist
    if [ ! -d /sbin ]; then
        mkdir -p /sbin
        mount -t tmpfs tmpfs /sbin
    fi
    cp "$ASTRA_SU" /sbin/su
    chmod 06755 /sbin/su
    log "astra_su installed to /sbin/su"
fi
"""

    script += """
log "AstraRoot init complete"
"""

    script_path = os.path.join(output_dir, "astra_init.sh")
    with open(script_path, 'w') as f:
        f.write(script)
    os.chmod(script_path, 0o755)
    return script_path


def create_vbmeta_disable(vbmeta_path: str, output_path: str):
    """
    Patch vbmeta to disable dm-verity verification.

    Reasoning: flashing a modified boot/vendor_boot triggers dm-verity
    verification failure. We set the vbmeta header flags field:
    - bit 0: disable verification
    - bit 1: disable dm-verity
    """
    if not os.path.exists(vbmeta_path):
        print("  WARN: vbmeta.img not found, skipping")
        return None

    with open(vbmeta_path, 'rb') as f:
        data = bytearray(f.read())

    # vbmeta header magic: "AVB0"
    if data[:4] != b'AVB0':
        print("  WARN: Not a valid vbmeta image")
        return None

    # flags field at offset 120 (big-endian uint32)
    # set bit 0 (disable verification) and bit 1 (disable verity)
    flags = struct.unpack('>I', data[120:124])[0]
    flags |= 0x03  # AVB_VBMETA_IMAGE_FLAGS_HASHTREE_DISABLED | VERIFICATION_DISABLED
    data[120:124] = struct.pack('>I', flags)

    with open(output_path, 'wb') as f:
        f.write(data)

    print(f"  -> vbmeta patched: flags=0x{flags:08x}")
    return output_path


def patch_image(boot_path: str, module_path: str, daemon_path: str,
                su_path: str, output_path: str, vbmeta_path: str = None):
    """Main patch flow"""
    tmpdir = tempfile.mkdtemp(prefix="astra_patch_")

    try:
        print("==========================================")
        print("  AstraRoot Boot Image Patcher v2")
        print("==========================================")
        print()

        # -- Step 1: detect boot image type --
        print("-- Step 1: Analyze boot image --")
        with open(boot_path, 'rb') as f:
            magic = f.read(8)

        is_vendor_boot = magic == b'VNDRBOOT'
        is_boot = magic[:8] == b'ANDROID!'

        if is_vendor_boot:
            print(f"  Type: vendor_boot (VNDRBOOT)")
        elif is_boot:
            print(f"  Type: boot (ANDROID!)")
        else:
            raise BootImageError(f"Unknown boot image format: {magic[:8]}")

        file_size = os.path.getsize(boot_path)
        print(f"  Size: {file_size} bytes ({file_size/1024/1024:.1f} MB)")

        # -- Step 2: unpack --
        print()
        print("-- Step 2: Unpack --")

        # Use magiskboot (if available) or manual unpack
        magiskboot = shutil.which('magiskboot')

        if magiskboot:
            print("  Using magiskboot")
            run_cmd(['magiskboot', 'unpack', boot_path], cwd=tmpdir)
            ramdisk_path = os.path.join(tmpdir, "ramdisk.cpio")
            if not os.path.exists(ramdisk_path):
                # Try other names
                for f in os.listdir(tmpdir):
                    if 'ramdisk' in f.lower():
                        ramdisk_path = os.path.join(tmpdir, f)
                        break
        else:
            print("  WARN: magiskboot not found, using Python extraction")
            print("  Please install magiskboot for full boot image support")
            print("  Trying basic extraction...")
            ramdisk_path = extract_ramdisk_basic(boot_path, tmpdir, is_vendor_boot)

        if not ramdisk_path or not os.path.exists(ramdisk_path):
            raise BootImageError("Cannot find ramdisk in boot image")

        print(f"  Ramdisk: {ramdisk_path}")
        compression = detect_compression(ramdisk_path)
        print(f"  Compression: {compression}")

        # -- Step 3: extract ramdisk --
        print()
        print("-- Step 3: Extract ramdisk --")
        ramdisk_dir = os.path.join(tmpdir, "ramdisk_root")

        if compression != 'none':
            decompressed = os.path.join(tmpdir, "ramdisk_decompressed.cpio")
            decompress(ramdisk_path, decompressed, compression)
            unpack_cpio(decompressed, ramdisk_dir)
        else:
            unpack_cpio(ramdisk_path, ramdisk_dir)

        file_count = sum(len(files) for _, _, files in os.walk(ramdisk_dir))
        print(f"  Extracted {file_count} files")

        # -- Step 4: inject files --
        print()
        print("-- Step 4: Inject files --")

        # 4a: kernel module
        if module_path and os.path.exists(module_path):
            modules_dir = os.path.join(ramdisk_dir, "lib", "modules")
            os.makedirs(modules_dir, exist_ok=True)
            shutil.copy2(module_path, os.path.join(modules_dir, "astra_root.ko"))
            print(f"  -> astra_root.ko -> lib/modules/")
        else:
            print("  WARN: astra_root.ko not provided")

        # 4b: astrad
        if daemon_path and os.path.exists(daemon_path):
            shutil.copy2(daemon_path, os.path.join(ramdisk_dir, "astrad"))
            os.chmod(os.path.join(ramdisk_dir, "astrad"), 0o755)
            print(f"  -> astrad -> /")
        else:
            print("  WARN: astrad not provided (will look in /data/adb/astraveil/)")

        # 4c: astra_su
        if su_path and os.path.exists(su_path):
            shutil.copy2(su_path, os.path.join(ramdisk_dir, "astra_su"))
            os.chmod(os.path.join(ramdisk_dir, "astra_su"), 0o755)
            print(f"  -> astra_su -> /")
        else:
            print("  WARN: astra_su not provided")

        # 4d: init script
        create_init_script(ramdisk_dir, daemon_path is not None, su_path is not None)
        print(f"  -> astra_init.sh created")

        # -- Step 5: patch init.rc --
        print()
        print("-- Step 5: Patch init.rc --")
        init_rc = os.path.join(ramdisk_dir, "init.rc")
        if os.path.exists(init_rc):
            with open(init_rc, 'r') as f:
                content = f.read()
            if 'astra_init.sh' not in content:
                with open(init_rc, 'a') as f:
                    f.write("\n# AstraRoot\non post-fs-data\n    exec -- /system/bin/sh /astra_init.sh\n")
                print("  -> init.rc patched")
            else:
                print("  -> init.rc already patched")
        else:
            # Create minimal init.rc
            with open(init_rc, 'w') as f:
                f.write("# AstraRoot\non post-fs-data\n    exec -- /system/bin/sh /astra_init.sh\n")
            print("  -> init.rc created")

        # -- Step 6: repack ramdisk --
        print()
        print("-- Step 6: Repack ramdisk --")
        new_cpio = os.path.join(tmpdir, "ramdisk_new.cpio")
        repack_cpio(ramdisk_dir, new_cpio)

        if compression != 'none':
            compress(new_cpio, ramdisk_path, compression)
        else:
            shutil.copy2(new_cpio, ramdisk_path)

        new_size = os.path.getsize(ramdisk_path)
        print(f"  -> Ramdisk repacked ({compression}, {new_size} bytes)")

        # -- Step 7: repack boot image --
        print()
        print("-- Step 7: Repack boot image --")

        if magiskboot:
            run_cmd(['magiskboot', 'repack', boot_path, output_path], cwd=tmpdir)
        else:
            print("  WARN: magiskboot not found, cannot repack")
            print("  Please install magiskboot:")
            print("    https://github.com/topjohnwu/Magisk/releases")
            sys.exit(1)

        final_size = os.path.getsize(output_path)
        print(f"  -> Output: {output_path} ({final_size/1024/1024:.1f} MB)")

        # -- Step 8: patch vbmeta --
        if vbmeta_path:
            print()
            print("-- Step 8: Patch vbmeta --")
            vbmeta_out = output_path.replace('.img', '_vbmeta.img')
            create_vbmeta_disable(vbmeta_path, vbmeta_out)

        # -- Step 9: SHA256 checksum --
        print()
        print("-- Step 9: Checksums --")
        with open(output_path, 'rb') as f:
            sha = hashlib.sha256(f.read()).hexdigest()
        print(f"  SHA256: {sha}")

        # -- done --
        print()
        print("==========================================")
        print(f"  OK: Output: {output_path}")
        print()
        print("  Flash commands:")
        print(f"    adb reboot bootloader")
        print(f"    fastboot flash {'vendor_boot' if is_vendor_boot else 'boot'} {output_path}")
        if vbmeta_path:
            print(f"    fastboot flash vbmeta --disable-verity --disable-verification vbmeta.img")
        print(f"    fastboot reboot")
        print()
        print("  Verify after reboot:")
        print(f"    adb shell ls -la /dev/astra_root")
        print(f"    adb shell cat /proc/modules | grep astra")
        print(f"    adb shell /sbin/su -c id")
        print("==========================================")

    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)


def extract_ramdisk_basic(boot_path: str, tmpdir: str, is_vendor_boot: bool) -> str:
    """
    Basic ramdisk extraction (fallback when magiskboot is unavailable).
    Only handles simple cases; complex boot images need magiskboot.
    """
    with open(boot_path, 'rb') as f:
        data = f.read()

    # Search for gzip/lz4/zstd magic
    for offset in range(0, min(len(data), 1024*1024), 4):
        chunk = data[offset:offset+4]
        if chunk == b'\x02\x21\x4c\x18':  # lz4
            ramdisk_path = os.path.join(tmpdir, "ramdisk.lz4")
            with open(ramdisk_path, 'wb') as f:
                f.write(data[offset:])
            return ramdisk_path
        elif chunk == b'\x1f\x8b':  # gzip
            ramdisk_path = os.path.join(tmpdir, "ramdisk.gz")
            with open(ramdisk_path, 'wb') as f:
                f.write(data[offset:])
            return ramdisk_path
        elif chunk == b'\x28\xb5\x2f\xfd':  # zstd
            ramdisk_path = os.path.join(tmpdir, "ramdisk.zst")
            with open(ramdisk_path, 'wb') as f:
                f.write(data[offset:])
            return ramdisk_path

    return None


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="AstraRoot Boot Image Patcher",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Patch vendor_boot with kernel module only
  python3 patch_boot.py --boot vendor_boot.img --module astra_root.ko --output patched.img

  # Full patch with daemon and su
  python3 patch_boot.py --boot vendor_boot.img --module astra_root.ko \\
    --daemon astrad --su astra_su --output patched.img

  # Also patch vbmeta
  python3 patch_boot.py --boot vendor_boot.img --module astra_root.ko \\
    --output patched.img --vbmeta vbmeta.img
        """
    )
    parser.add_argument("--boot", required=True, help="boot.img or vendor_boot.img path")
    parser.add_argument("--module", required=True, help="astra_root.ko path")
    parser.add_argument("--daemon", default="", help="astrad binary path (optional)")
    parser.add_argument("--su", default="", help="astra_su binary path (optional)")
    parser.add_argument("--output", required=True, help="output patched image path")
    parser.add_argument("--vbmeta", default="", help="vbmeta.img path (optional, for dm-verity disable)")

    args = parser.parse_args()

    if not os.path.exists(args.boot):
        print(f"ERROR: Boot image not found: {args.boot}")
        sys.exit(1)
    if not os.path.exists(args.module):
        print(f"ERROR: Kernel module not found: {args.module}")
        sys.exit(1)

    patch_image(
        boot_path=args.boot,
        module_path=args.module,
        daemon_path=args.daemon if args.daemon else None,
        su_path=args.su if args.su else None,
        output_path=args.output,
        vbmeta_path=args.vbmeta if args.vbmeta else None,
    )
