package com.astraveil.modules.runtime.sandbox

import kotlinx.serialization.Serializable

/**
 * v3 sandbox profile — the restriction set applied to a module process.
 *
 * Generated by [SandboxPolicyResolver] from the module's risk level.
 * The module cannot decide its own profile; the system derives it from
 * the manifest's declared permissions + risk.
 */
@Serializable
data class SandboxProfile(
    val filesystem: Boolean,
    val namespace: Boolean,
    val property: Boolean,
    val maxRisk: Int,
)
